redis_ambassador:
  container_name: "redis_ambassador"
  image: svendowideit/ambassador
  expose:
   - "6379"
  environment:
   REDIS_PORT_6379_TCP: tcp://10.139.56.55:6379

client:
  container_name: "client"
  image: relateiq/redis-cli
  links:
   - redis_ambassador:redis
